### ISSUE TITLE
Where is the options to change colors?

### ISSUE THREAD

**Issue by lexterror** [TheWisker/Cavasik#1]
### Explanation

Hi, I installed your app on both Elementary Os and Pop Os without flatpak. I dont see any options to change the color of the visualization. Could you please let me know how to do this? Thank you!

### Expected Behavior

Easier way to change colors?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment]
If you hover over the top left corner of the visualizer window you should see a hamburger button. After clicking on it a drop-down menu should appear. One of the options of said menu is "Preferences" which upon click should open the preferences window.  Also you can open the preferences window by pressing the P key with the Cavasik application focused.

Then in the bottom bar of the preferences window you need to click "Colors" and that opens up the color configuration tab. From there you can customize the colors, color profiles and color animation.

Here are some screenshots that can be of help:

<div align="center">

![2023-07-06_16-57](https://github.com/TheWisker/Cavasik/assets/89247044/7ed7f289-8738-472a-b2a5-ac8f7dacb7b0)
![2023-07-06_16-58](https://github.com/TheWisker/Cavasik/assets/89247044/e776f536-933c-404b-8170-dcbbd72f28a9)

</div>

**Comment by lexterror** [comment]
All those color options are not visible on my panel

**Comment by lexterror** [comment]
it has to do with the home location of "gi" Ive been working on it since the last post. It cant find the module. Although I have everything installed.

**Comment by lexterror** [comment]
the exact error is: 

Attribute Error gi.repository.gtk object has no attribute colordialog

**Comment by lexterror** [comment]
Sorry I did not post screenshots before. I felt a bit guilty by bring in up this issue because I did not follow the regular setup. I really did not want to bother anyone. But having gradients is kind of neat.

![Screenshot from 2023-07-06 23 05 05](https://github.com/TheWisker/Cavasik/assets/16135535/2b6d489b-4066-445f-a613-ac46479f4dcc)

![Screenshot from 2023-07-06 23 05 43](https://github.com/TheWisker/Cavasik/assets/16135535/6b0332c1-16e9-47b3-bc4f-69aaaea18da4)

**Comment by lexterror** [comment]
I installed from flatpak everything works.
I have one last comment:

Do you think you could provide an AppImage in the future please?

Thank you!

**Comment by TheWisker** [comment]
When not installing from the normal sources you need to install the dependencies manually. The problem could have been the Gtk version installed or something similar.

About the appimage, I will take a look at it to provide more diverse and reliable installation options!

Thanks for the support!

**Comment by Kellsen** [comment]
OK, super late to the party but I just stumbled across Cavasik and encountered the exact same problem and the "solution"...well, it's no solution but an explanation is (at least for me using Debian 12) fairly simple: the installed gtk4 version just doesn't have the "ColorDialog" implemented. That only comes with gtk4 version 4.10 and newer. Check for your libgtk-4-1 package. Debian bookworm has 4.8.3 so this option is just not available yet. And I won't be upgrading to a newer version because then I'd be building a Franken-Debian and go to dependency hell. I just use the Flatpkak.

see here:
https://docs.gtk.org/gtk4/class.ColorDialog.html
