### ISSUE TITLE
[Enhancement] Sync Color Profile & Mirrored Color Profile

### ISSUE THREAD

**Issue by MylesGit** [TheWisker/Cavasik#2]
### Explanation

When you change the color profile the mirrored color profile does not change with it. I would suggest adding on toggle for this feature!

### Expected Behavior

When you change the color profile the mirrored color profile changes with it to the color profile you selected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment]
This should be really easy to do so I will work on it! Thanks for the enhancement suggestion!

**Comment by TheWisker** [comment]
Sorry for taking so really long to do it! I will make a update in a few hours containing this enhancement. Thank you for your patience and your ideas!

**Comment by TheWisker** [comment]
I have just made the [update](https://github.com/TheWisker/Cavasik/releases/tag/v2.0.1). Hope you like it and sorry for the delay. Thanks for the idea!
