### ISSUE TITLE
[Enhancement] Add a toggle to remove the tint from mirrored mode.

### ISSUE THREAD

**Issue by MylesGit** [TheWisker/Cavasik#3]
### Explanation

Add a toggle to remove the tint from mirrored mode.

### Expected Behavior

Clicking on a toggle button for "Mirror Glint" will get rid of the slight darkness/tint to the mirrored side.

### Additional Context

I do not mean to spam this repo with enhancements so I'll just post these two. If you would like to follow up in the comments I would be happy to talk! 

I'd also like to say that I am super impressed with this re-written project. It offers more features and better performance. Props to all the developers of this project!

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment]
About the tint, there is no **real** tint (value or option) for the mirrored image, it is just a **opacity** value below 100. To get rid of that you just have to set the opacity to 100 with the slider.

<div align="center">

![2023-07-22_10-34](https://github.com/TheWisker/Cavasik/assets/89247044/c118e1b3-5bb6-4b67-a95c-6bedd444fbf8)

</div>

If that is not what you were **referring** to or expecting to add/change please reword the explanation or give more details as I cannot fully understand you.

Also, **thanks** for the props as I am currently the only developer working on this. I will gladly **follow up** with you in the comments!  I am here to help!

**Comment by MylesGit** [comment]
> About the tint, there is no **real** tint (value or option) for the mirrored image, it is just a **opacity** value below 100. To get rid of that you just have to set the opacity to 100 with the slider.

You are correct, completely glossed past that option.
