### ISSUE TITLE
[BUG] Noise reduction is not working?

### ISSUE THREAD

**Issue by d3cryptofc** [TheWisker/Cavasik#4]
### Explanation

I've Cava 0.9.1 on my system, it seems that noise reduction value must be between 0 and 100, not 0 and 1.

I tried to edit `~/.config/cavasik/config` file, but it restores value to 1.0.

### Cavasik Version

v1.0.0

### Linux Distro

Arch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by d3cryptofc** [comment]
Thank you for answering this issue :)

I changed the file `/usr/share/cavasik/cavasik/cava.py` on line 62:
https://github.com/TheWisker/Cavasik/blob/master/src/cava.py#L62

```python3
self.noise_reduction = self.settings['noise-reduction']
```

to
```python3
self.noise_reduction = self.settings['noise-reduction'] * 100
```

It seems to work right for me..

**Comment by TheWisker** [comment]
It is really strange, the change you did to cava.py was one of the changes I did while performing some tests that caused the output to saturate (glitch). So in the end I do not know if I should change it in the release version or let it as it is.

**Comment by d3cryptofc** [comment]
Really.. Just in case I'll leave my configuration file here in case you need it.

**~/.config/cavasik/config** 
```
[general]
bars = 100
autosens = 1
sensitivity = 100.0
framerate = 30
[input]
method = pulse
[output]
channels = stereo
mono_option = average
method = raw
raw_target = /dev/stdout
bit_format = 16bit
[smoothing]
monstercat = 1
noise_reduction = 39.0
```

**Comment by d3cryptofc** [comment]
Your case is really strange, because here is working fine.. This is my suggestion:

```python3
import subprocess

_, cava_version = subprocess.getoutput('cava -v').split()

self.noise_reduction = (
   self.settings['noise-reduction'] * (100 if cava_version >= '0.9' else 1)
)
```

**Comment by Plyply99** [comment]
I have exact same issue on a fresh Arch install. Cava uses a value 0 - 100.

"self.noise_reduction = self.settings['noise-reduction'] * 100" fixed it for me too.
