### ISSUE TITLE
[Enhancement] Transparent background

### ISSUE THREAD

**Issue by Myzel394** [TheWisker/Cavasik#6]
### Explanation

Having the option to make the background would make this absolutely aesthetic.

### Expected Behavior

In the settings there should be an option to make the background transparent.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheWisker** [comment]
There is not any explicit option to make the background transparent at the moment, but when choosing a background color in the colors menu, you can set the color to be transparent which basically makes the entire background transparent.

**Comment by Myzel394** [comment]
I just tried that out - but seems like I can't set the background color at all :/

**Comment by TheWisker** [comment]
After selecting a color have you clicked on the plus sign next to the color? Sometimes I forget to do it.

**Comment by Myzel394** [comment]
> After selecting a color have you clicked on the plus sign next to the color? Sometimes I forget to do it.

That was the issue. thanks for the quick response :D

**Comment by TheWisker** [comment]
It's nothing, that part of the user interface is not as intuitive as it should be.
